steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vitalink-backend:$COMMIT_SHA', './backend']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/vitalink-backend:$COMMIT_SHA']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - vitalink-backend-dev
      - --image=gcr.io/$PROJECT_ID/vitalink-backend:$COMMIT_SHA
      - --region=africa-south1
      - --platform=managed
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vitalink-web:$COMMIT_SHA', '-f', 'web/Dockerfile', './web']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/vitalink-web:$COMMIT_SHA']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - vitalink-web-dev
      - --image=gcr.io/$PROJECT_ID/vitalink-web:$COMMIT_SHA
      - --region=africa-south1
      - --platform=managed

images:
  - gcr.io/$PROJECT_ID/vitalink-backend:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/vitalink-web:$COMMIT_SHA
